package openfl.display;

@:access(openfl.events.Event) @:access(openfl.display.Graphics) @:access(openfl.display.Stage) @:access(openfl.geom.ColorTransform) @:access(openfl.geom.Rectangle) extern class DisplayObject extends openfl.events.EventDispatcher implements IBitmapDrawable {
	@:dox(hide) @:noCompletion var __worldColorTransform : openfl.geom.ColorTransform;
	@:dox(hide) @:noCompletion var __worldTransform : openfl.geom.Matrix;
	var alpha(get,set) : Float;
	var blendMode(default,set) : BlendMode;
	var cacheAsBitmap : Bool;
	var filters(get,set) : Array<openfl.filters.BitmapFilter>;
	var height(get,set) : Float;
	var loaderInfo : LoaderInfo;
	var mask(get,set) : DisplayObject;
	var mouseX(get,null) : Float;
	var mouseY(get,null) : Float;
	var name(get,set) : String;
	var opaqueBackground : Null<Int>;
	var parent(default,null) : DisplayObjectContainer;
	var root(get,null) : DisplayObject;
	var rotation(get,set) : Float;
	var scale9Grid : openfl.geom.Rectangle;
	var scaleX(get,set) : Float;
	var scaleY(get,set) : Float;
	var scrollRect(get,set) : openfl.geom.Rectangle;
	var stage(default,null) : Stage;
	var transform(get,set) : openfl.geom.Transform;
	var visible(get,set) : Bool;
	var width(get,set) : Float;
	var x(get,set) : Float;
	var y(get,set) : Float;
	@:noCompletion @:dox(hide) function __renderCairo(renderSession : openfl._internal.renderer.RenderSession) : Void;
	@:noCompletion @:dox(hide) function __renderCairoMask(renderSession : openfl._internal.renderer.RenderSession) : Void;
	@:noCompletion @:dox(hide) function __renderCanvas(renderSession : openfl._internal.renderer.RenderSession) : Void;
	@:noCompletion @:dox(hide) function __renderCanvasMask(renderSession : openfl._internal.renderer.RenderSession) : Void;
	@:noCompletion @:dox(hide) function __renderDOM(renderSession : openfl._internal.renderer.RenderSession) : Void;
	@:noCompletion @:dox(hide) function __renderGL(renderSession : openfl._internal.renderer.RenderSession) : Void;
	@:noCompletion @:dox(hide) function __update(transformOnly : Bool, updateChildren : Bool, ?maskGraphics : Graphics) : Void;
	@:noCompletion @:dox(hide) function __updateChildren(transformOnly : Bool) : Void;
	@:noCompletion @:dox(hide) function __updateMask(maskGraphics : Graphics) : Void;
	function getBounds(targetCoordinateSpace : DisplayObject) : openfl.geom.Rectangle;
	function getRect(targetCoordinateSpace : DisplayObject) : openfl.geom.Rectangle;
	function globalToLocal(pos : openfl.geom.Point) : openfl.geom.Point;
	function hitTestObject(obj : DisplayObject) : Bool;
	function hitTestPoint(x : Float, y : Float, shapeFlag : Bool = false) : Bool;
	function localToGlobal(point : openfl.geom.Point) : openfl.geom.Point;
	private function __setRenderDirty () : Void;
	@:noCompletion private var __graphics:Graphics;
	@:noCompletion private var __blendMode:BlendMode;
	@:noCompletion private var __worldAlpha:Float;
}
