package lime.ui;

extern class Window {
	var config : lime.app.Config;
	var currentRenderer : lime.graphics.Renderer;
	var display(get,null) : lime.system.Display;
	var enableTextEvents(get,set) : Bool;
	var fullscreen(get,set) : Bool;
	var height(get,set) : Int;
	var minimized(get,set) : Bool;
	var onGamepadAxisMove : lime.app.Event<Gamepad -> GamepadAxis -> Float -> Void>;
	var onGamepadButtonDown : lime.app.Event<Gamepad -> GamepadButton -> Void>;
	var onGamepadButtonUp : lime.app.Event<Gamepad -> GamepadButton -> Void>;
	var onGamepadConnect : lime.app.Event<Gamepad -> Void>;
	var onGamepadDisconnect : lime.app.Event<Gamepad -> Void>;
	var onKeyDown : lime.app.Event<KeyCode -> KeyModifier -> Void>;
	var onKeyUp : lime.app.Event<KeyCode -> KeyModifier -> Void>;
	var onMouseDown : lime.app.Event<Float -> Float -> Int -> Void>;
	var onMouseMove : lime.app.Event<Float -> Float -> Void>;
	var onMouseMoveRelative : lime.app.Event<Float -> Float -> Void>;
	var onMouseUp : lime.app.Event<Float -> Float -> Int -> Void>;
	var onMouseWheel : lime.app.Event<Float -> Float -> Void>;
	var onTextEdit : lime.app.Event<String -> Int -> Int -> Void>;
	var onTextInput : lime.app.Event<String -> Void>;
	var onTouchEnd : lime.app.Event<Float -> Float -> Int -> Void>;
	var onTouchMove : lime.app.Event<Float -> Float -> Int -> Void>;
	var onTouchStart : lime.app.Event<Float -> Float -> Int -> Void>;
	var onWindowActivate : lime.app.Event<Void -> Void>;
	var onWindowClose : lime.app.Event<Void -> Void>;
	var onWindowDeactivate : lime.app.Event<Void -> Void>;
	var onWindowEnter : lime.app.Event<Void -> Void>;
	var onWindowFocusIn : lime.app.Event<Void -> Void>;
	var onWindowFocusOut : lime.app.Event<Void -> Void>;
	var onWindowFullscreen : lime.app.Event<Void -> Void>;
	var onWindowLeave : lime.app.Event<Void -> Void>;
	var onWindowMinimize : lime.app.Event<Void -> Void>;
	var onWindowMove : lime.app.Event<Float -> Float -> Void>;
	var onWindowResize : lime.app.Event<Int -> Int -> Void>;
	var onWindowRestore : lime.app.Event<Void -> Void>;
	var title(get,set) : String;
	var width(get,set) : Int;
	var x(get,set) : Int;
	var y(get,set) : Int;
	function new(?config : lime.app.Config) : Void;
	function close() : Void;
	function create(application : lime.app.Application) : Void;
	function move(x : Int, y : Int) : Void;
	function resize(width : Int, height : Int) : Void;
	function setIcon(image : lime.graphics.Image) : Void;
}
