package lime.audio;

extern class HTML5AudioContext {
	var HAVE_CURRENT_DATA : Int;
	var HAVE_ENOUGH_DATA : Int;
	var HAVE_FUTURE_DATA : Int;
	var HAVE_METADATA : Int;
	var HAVE_NOTHING : Int;
	var NETWORK_EMPTY : Int;
	var NETWORK_IDLE : Int;
	var NETWORK_LOADING : Int;
	var NETWORK_NO_SOURCE : Int;
	function new() : Void;
	function canPlayType(buffer : AudioBuffer, type : String) : String;
	function createBuffer(?urlString : String) : AudioBuffer;
	function getAutoplay(buffer : AudioBuffer) : Bool;
	function getBuffered(buffer : AudioBuffer) : Dynamic;
	function getCurrentSrc(buffer : AudioBuffer) : String;
	function getCurrentTime(buffer : AudioBuffer) : Float;
	function getDefaultPlaybackRate(buffer : AudioBuffer) : Float;
	function getDuration(buffer : AudioBuffer) : Float;
	function getEnded(buffer : AudioBuffer) : Bool;
	function getError(buffer : AudioBuffer) : Dynamic;
	function getLoop(buffer : AudioBuffer) : Bool;
	function getMuted(buffer : AudioBuffer) : Bool;
	function getNetworkState(buffer : AudioBuffer) : Int;
	function getPaused(buffer : AudioBuffer) : Bool;
	function getPlaybackRate(buffer : AudioBuffer) : Float;
	function getPlayed(buffer : AudioBuffer) : Dynamic;
	function getPreload(buffer : AudioBuffer) : String;
	function getReadyState(buffer : AudioBuffer) : Int;
	function getSeekable(buffer : AudioBuffer) : Dynamic;
	function getSeeking(buffer : AudioBuffer) : Bool;
	function getSrc(buffer : AudioBuffer) : String;
	function getStartTime(buffer : AudioBuffer) : Float;
	function getVolume(buffer : AudioBuffer) : Float;
	function load(buffer : AudioBuffer) : Void;
	function pause(buffer : AudioBuffer) : Void;
	function play(buffer : AudioBuffer) : Void;
	function setAutoplay(buffer : AudioBuffer, value : Bool) : Void;
	function setCurrentTime(buffer : AudioBuffer, value : Float) : Void;
	function setDefaultPlaybackRate(buffer : AudioBuffer, value : Float) : Void;
	function setLoop(buffer : AudioBuffer, value : Bool) : Void;
	function setMuted(buffer : AudioBuffer, value : Bool) : Void;
	function setPlaybackRate(buffer : AudioBuffer, value : Float) : Void;
	function setPreload(buffer : AudioBuffer, value : String) : Void;
	function setSrc(buffer : AudioBuffer, value : String) : Void;
	function setVolume(buffer : AudioBuffer, value : Float) : Void;
}
