package openfl.text;

@:access(openfl.display.Graphics) @:access(openfl.geom.Rectangle) @:access(openfl.text.TextFormat) extern class TextField extends openfl.display.InteractiveObject {
	var antiAliasType(get,set) : AntiAliasType;
	var autoSize(get,set) : TextFieldAutoSize;
	var background(get,set) : Bool;
	var backgroundColor(get,set) : Int;
	var border(get,set) : Bool;
	var borderColor(get,set) : Int;
	var bottomScrollV(get,null) : Int;
	var caretIndex(get,null) : Int;
	var defaultTextFormat(get,set) : TextFormat;
	var displayAsPassword(get,set) : Bool;
	var embedFonts(get,set) : Bool;
	var gridFitType(get,set) : GridFitType;
	var htmlText(get,set) : String;
	var length(get,null) : Int;
	var maxChars(get,set) : Int;
	var maxScrollH(get,null) : Int;
	var maxScrollV(get,null) : Int;
	var multiline(get,set) : Bool;
	var numLines(get,null) : Int;
	var restrict(get,set) : String;
	var scrollH(get,set) : Int;
	var scrollV(get,set) : Int;
	var selectable(get,set) : Bool;
	var selectionBeginIndex(get,null) : Int;
	var selectionEndIndex(get,null) : Int;
	var sharpness(get,set) : Float;
	var text(get,set) : String;
	var textColor(get,set) : Int;
	var textHeight(get,null) : Float;
	var textWidth(get,null) : Float;
	var type(get,set) : TextFieldType;
	var wordWrap(get,set) : Bool;
	function new() : Void;
	function appendText(text : String) : Void;
	function getCharBoundaries(a : Int) : openfl.geom.Rectangle;
	function getCharIndexAtPoint(x : Float, y : Float) : Int;
	function getLineIndexAtPoint(x : Float, y : Float) : Int;
	function getLineMetrics(lineIndex : Int) : TextLineMetrics;
	function getLineOffset(lineIndex : Int) : Int;
	function getLineText(lineIndex : Int) : String;
	function getTextFormat(beginIndex : Int = 0, endIndex : Int = 0) : TextFormat;
	function setSelection(beginIndex : Int, endIndex : Int) : Void;
	function setTextFormat(format : TextFormat, beginIndex : Int = 0, endIndex : Int = 0) : Void;
}
