package lime.graphics.cairo;

extern class Cairo {
	var antialias(get,set) : CairoAntialias;
	var currentPoint(get,never) : lime.math.Vector2;
	var dash(get,set) : Array<Float>;
	var dashCount(get,never) : Int;
	var fillRule(get,set) : CairoFillRule;
	var groupTarget(get,never) : CairoSurface;
	var hasCurrentPoint(get,never) : Bool;
	var lineCap(get,set) : CairoLineCap;
	var lineJoin(get,set) : CairoLineJoin;
	var lineWidth(get,set) : Float;
	var matrix(get,set) : lime.math.Matrix3;
	var miterLimit(get,set) : Float;
	var operator(get,set) : CairoOperator;
	var referenceCount(get,never) : Int;
	var source(get,set) : CairoPattern;
	var target(get,null) : CairoSurface;
	var tolerance(get,set) : Float;
	var userData : Dynamic;
	function new(?surface : CairoSurface) : Void;
	function arc(xc : Float, yc : Float, radius : Float, angle1 : Float, angle2 : Float) : Void;
	function arcNegative(xc : Float, yc : Float, radius : Float, angle1 : Float, angle2 : Float) : Void;
	function clip() : Void;
	function clipExtents(x1 : Float, y1 : Float, x2 : Float, y2 : Float) : Void;
	function clipPreserve() : Void;
	function closePath() : Void;
	function copyPage() : Void;
	function curveTo(x1 : Float, y1 : Float, x2 : Float, y2 : Float, x3 : Float, y3 : Float) : Void;
	function destroy() : Void;
	function fill() : Void;
	function fillExtents(x1 : Float, y1 : Float, x2 : Float, y2 : Float) : Void;
	function fillPreserve() : Void;
	function getFontOptions() : CairoFontOptions;
	function identityMatrix() : Void;
	function inClip(x : Float, y : Float) : Bool;
	function inFill(x : Float, y : Float) : Bool;
	function inStroke(x : Float, y : Float) : Bool;
	function lineTo(x : Float, y : Float) : Void;
	function mask(pattern : CairoPattern) : Void;
	function maskSurface(surface : CairoSurface, x : Float, y : Float) : Void;
	function moveTo(x : Float, y : Float) : Void;
	function newPath() : Void;
	function paint() : Void;
	function paintWithAlpha(alpha : Float) : Void;
	function popGroup() : CairoPattern;
	function popGroupToSource() : Void;
	function pushGroup() : Void;
	function pushGroupWithContent(content : CairoContent) : Void;
	function recreate(surface : CairoSurface) : Void;
	function rectangle(x : Float, y : Float, width : Float, height : Float) : Void;
	function reference() : Void;
	function relCurveTo(dx1 : Float, dy1 : Float, dx2 : Float, dy2 : Float, dx3 : Float, dy3 : Float) : Void;
	function relLineTo(dx : Float, dy : Float) : Void;
	function relMoveTo(dx : Float, dy : Float) : Void;
	function resetClip() : Void;
	function restore() : Void;
	function rotate(amount : Float) : Void;
	function save() : Void;
	function scale(x : Float, y : Float) : Void;
	function setFontFace(face : CairoFont) : Void;
	function setFontOptions(value : CairoFontOptions) : CairoFontOptions;
	function setFontSize(size : Float) : Void;
	function setSourceRGB(r : Float, g : Float, b : Float) : Void;
	function setSourceRGBA(r : Float, g : Float, b : Float, a : Float) : Void;
	function setSourceSurface(surface : CairoSurface, x : Float, y : Float) : Void;
	function showPage() : Void;
	function showText(utf8 : String) : Void;
	function status() : CairoStatus;
	function stroke() : Void;
	function strokeExtents(x1 : Float, y1 : Float, x2 : Float, y2 : Float) : Void;
	function strokePreserve() : Void;
	function transform(matrix : lime.math.Matrix3) : Void;
	function translate(x : Float, y : Float) : Void;
	static var version(get,null) : Int;
	static var versionString(get,null) : String;
}
