package openfl.geom;

extern class Matrix {
	var a : Float;
	var b : Float;
	var c : Float;
	var d : Float;
	var tx : Float;
	var ty : Float;
	function new(a : Float = 0, b : Float = 0, c : Float = 0, d : Float = 0, tx : Float = 0, ty : Float = 0) : Void;
	@:noCompletion function __transformInversePoint(point : Point) : Void;
	@:noCompletion function __transformInverseX(px : Float, py : Float) : Float;
	@:noCompletion function __transformInverseY(px : Float, py : Float) : Float;
	@:noCompletion function __transformPoint(point : Point) : Void;
	@:noCompletion function __transformX(px : Float, py : Float) : Float;
	@:noCompletion function __transformY(px : Float, py : Float) : Float;
	@:noCompletion function __translateTransformed(px : Float, py : Float) : Void;
	function clone() : Matrix;
	function concat(m : Matrix) : Void;
	function copyColumnFrom(column : Int, vector3D : Vector3D) : Void;
	function copyColumnTo(column : Int, vector3D : Vector3D) : Void;
	function copyFrom(sourceMatrix : Matrix) : Void;
	function copyRowFrom(row : Int, vector3D : Vector3D) : Void;
	function copyRowTo(row : Int, vector3D : Vector3D) : Void;
	function createBox(scaleX : Float, scaleY : Float, rotation : Float = 0, tx : Float = 0, ty : Float = 0) : Void;
	function createGradientBox(width : Float, height : Float, rotation : Float = 0, tx : Float = 0, ty : Float = 0) : Void;
	function deltaTransformPoint(point : Point) : Point;
	function equals(matrix : {ty : Float, tx : Float, d : Float, c : Float, b : Float, a : Float}) : Bool;
	function identity() : Void;
	function invert() : Matrix;
	function rotate(theta : Float) : Void;
	function scale(sx : Float, sy : Float) : Void;
	function setTo(a : Float, b : Float, c : Float, d : Float, tx : Float, ty : Float) : Void;
	function to3DString(roundPixels : Bool = false) : String;
	function toMozString() : String;
	function toString() : String;
	function transformPoint(pos : Point) : Point;
	function translate(dx : Float, dy : Float) : Void;
	@:noCompletion private function toArray (transpose:Bool = false):lime.utils.Float32Array;
	@:noCompletion private static var __identity : Matrix;
}
