package lime.graphics.cairo._CairoStatus;

@:enum extern class lime.graphics.cairo.priv_CairoStatus.CairoStatus_Impl_ {
	@:enum @:impl static var CLIP_NOT_REPRESENTABLE(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var DEVICE_ERROR(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var DEVICE_FINISHED(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var DEVICE_TYPE_MISMATCH(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var FILE_NOT_FOUND(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var FONT_TYPE_MISMATCH(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var INVALID_CLUSTERS(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var INVALID_CONTENT(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var INVALID_DASH(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var INVALID_DSC_COMMENT(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var INVALID_FORMAT(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var INVALID_INDEX(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var INVALID_MATRIX(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var INVALID_MESH_CONSTRUCTION(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var INVALID_PATH_DATA(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var INVALID_POP_GROUP(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var INVALID_RESTORE(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var INVALID_SIZE(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var INVALID_SLANT(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var INVALID_STATUS(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var INVALID_STRIDE(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var INVALID_STRING(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var INVALID_VISUAL(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var INVALID_WEIGHT(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var JBIG2_GLOBAL_MISSING(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var NEGATIVE_COUNT(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var NO_CURRENT_POINT(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var NO_MEMORY(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var NULL_POINTER(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var PATTERN_TYPE_MISMATCH(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var READ_ERROR(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var SUCCESS(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var SURFACE_FINISHED(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var SURFACE_TYPE_MISMATCH(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var TEMP_FILE_ERROR(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var USER_FONT_ERROR(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var USER_FONT_IMMUTABLE(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var USER_FONT_NOT_IMPLEMENTED(inline,never) : lime.graphics.cairo.CairoStatus;
	@:enum @:impl static var WRITE_ERROR(inline,never) : lime.graphics.cairo.CairoStatus;
}
