package lime.graphics;

extern class FlashRenderContext {
	var accessibilityImplementation : Dynamic;
	var accessibilityProperties : Dynamic;
	var alpha : Float;
	var blendMode : Dynamic;
	var blendShader(null,default) : Dynamic;
	var buttonMode : Bool;
	var cacheAsBitmap : Bool;
	var contextMenu : Dynamic;
	var doubleClickEnabled : Bool;
	var dropTarget(default,null) : Dynamic;
	var filters : Array<Dynamic>;
	var focusRect : Dynamic;
	var graphics(default,null) : Dynamic;
	var height : Float;
	var hitArea : Dynamic;
	var loaderInfo(default,null) : Dynamic;
	var mask : Dynamic;
	var mouseChildren : Bool;
	var mouseEnabled : Bool;
	var mouseX(default,null) : Float;
	var mouseY(default,null) : Float;
	var name : String;
	var needsSoftKeyboard : Bool;
	var numChildren(default,null) : Int;
	var opaqueBackground : Null<UInt>;
	var parent(default,null) : Dynamic;
	var root(default,null) : Dynamic;
	var rotation : Float;
	var rotationX : Float;
	var rotationY : Float;
	var rotationZ : Float;
	var scale9Grid : Dynamic;
	var scaleX : Float;
	var scaleY : Float;
	var scaleZ : Float;
	var scrollRect : Dynamic;
	var softKeyboardInputAreaOfInterest : Dynamic;
	var soundTransform : Dynamic;
	var stage(default,null) : Dynamic;
	var tabChildren : Bool;
	var tabEnabled : Bool;
	var tabIndex : Int;
	var textSnapshot(default,null) : Dynamic;
	var transform : Dynamic;
	var useHandCursor : Bool;
	var visible : Bool;
	var width : Float;
	var x : Float;
	var y : Float;
	var z : Float;
	function new() : Void;
	function addChild(child : Dynamic) : Dynamic;
	function addChildAt(child : Dynamic, index : Int) : Dynamic;
	function addEventListener(type : String, listener : Dynamic -> Void, useCapture : Bool = false, priority : Int = 0, useWeakReference : Bool = false) : Void;
	function areInaccessibleObjectsUnderPoint(point : Dynamic) : Bool;
	function contains(child : Dynamic) : Bool;
	function dispatchEvent(event : Dynamic) : Bool;
	function getBounds(targetCoordinateSpace : Dynamic) : Dynamic;
	function getChildAt(index : Int) : Dynamic;
	function getChildByName(name : String) : Dynamic;
	function getChildIndex(child : Dynamic) : Int;
	function getObjectsUnderPoint(point : Dynamic) : Array<Dynamic>;
	function getRect(targetCoordinateSpace : Dynamic) : Dynamic;
	function globalToLocal(point : Dynamic) : Dynamic;
	function globalToLocal3D(point : Dynamic) : Dynamic;
	function hasEventListener(type : String) : Bool;
	function hitTestObject(obj : Dynamic) : Bool;
	function hitTestPoint(x : Float, y : Float, shapeFlag : Bool = false) : Bool;
	function local3DToGlobal(point3d : Dynamic) : Dynamic;
	function localToGlobal(point : Dynamic) : Dynamic;
	function removeChild(child : Dynamic) : Dynamic;
	function removeChildAt(index : Int) : Dynamic;
	function removeChildren(beginIndex : Int = 0, endIndex : Int = 0) : Void;
	function removeEventListener(type : String, listener : Dynamic -> Void, useCapture : Bool = false) : Void;
	function requestSoftKeyboard() : Bool;
	function setChildIndex(child : Dynamic, index : Int) : Void;
	function startDrag(lockCenter : Bool = false, ?bounds : Dynamic) : Void;
	function startTouchDrag(touchPointID : Int, lockCenter : Bool = false, ?bounds : Dynamic) : Void;
	function stopAllMovieClips() : Void;
	function stopDrag() : Void;
	function stopTouchDrag(touchPointID : Int) : Void;
	function swapChildren(child1 : Dynamic, child2 : Dynamic) : Void;
	function swapChildrenAt(index1 : Int, index2 : Int) : Void;
	function toString() : String;
	function willTrigger(type : String) : Bool;
}
